### PR TITLE
Fix performance issue #37.

### PR DESCRIPTION
**Pull request by lichtsinn**
Code changes should improve performance quite a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/jiecao-fm/hashids-java/38)

### CODE REVIEW

**Comment by 0x3333** [comment]
Asked for just a small change. Nice catch!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/hashids/Hashids.java, line 356 at r1](https://reviewable.io:443/reviews/jiecao-fm/hashids-java/38#-Kb2-s65Hts8LXK5sjOl:-Kb2-s66h1Y5wpoHPAAF:b-2whxe1) ([raw file](https://github.com/jiecao-fm/hashids-java/blob/3108285cca600e32054e8b67bea932bbb757dee2/src/main/java/org/hashids/Hashids.java#L356)):*
> ```Java
> 
>     int asc_val, j;
>     char[] tmp_arr = alphabet.toCharArray();
> ```

Could you change `tmp_arr` to `tmpArr`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jiecao-fm/hashids-java/38#-:-Kb20P4iOz91FiM30nD1:b-5tlukh)*

**Comment by 0x3333** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jiecao-fm/hashids-java/38)*

**Comment by 0x3333** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jiecao-fm/hashids-java/38)*

**Comment by 0x3333** [comment]
Great. I'll merge it asap... I'm on the go...

Thanks for the patch!

**Comment by lichtsinn** [comment]
Still 'on the go...'?

**Comment by 0x3333** [comment]
Sorry for the delay, just got to the office today!

**Pull request merged**
